package biggie

import (
	_ "embed"
	"strings"
)

//go:embed tokens.css
var tokensCSS string

var LandingHTML = strings.Replace(`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>biggie-kun · big context, one chat</title><meta name="description" content="One billion tokens. One simple chat API.">
<link rel="icon" href="/favicon.svg"><link rel="preload" href="/logo-loop.webp" as="image" type="image/webp" fetchpriority="high"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@12..96,700&family=IBM+Plex+Sans:wght@400;700&family=JetBrains+Mono:wght@400;600&display=swap" rel="stylesheet">
<style>{{TOKENS}}
*{box-sizing:border-box}html,body{overflow-x:clip}body{margin:0;background:radial-gradient(circle at 76% 9%,color-mix(in oklch,var(--color-halo) 34%,transparent),transparent 29rem),var(--color-paper);color:var(--color-ink);font:var(--text-base)/1.62 var(--font-body);font-variant-numeric:oldstyle-nums}a{color:inherit;text-decoration-thickness:var(--rule-thin);text-underline-offset:var(--space-2xs);white-space:nowrap;transition:color var(--dur-micro) var(--ease-out)}a:hover{color:var(--color-accent-soft)}a:focus-visible{outline:var(--rule-focus) solid var(--color-focus);outline-offset:var(--space-2xs)}a:active{color:var(--color-focus)}code{font-family:var(--font-mono)}
.shell{width:min(var(--shell),calc(100% - var(--space-xl)));margin-inline:auto}.nav{position:fixed;inset:var(--space-md) auto auto 50%;z-index:var(--z-sticky);display:flex;align-items:center;gap:var(--space-sm);width:max-content;max-width:calc(100% - var(--space-xl));min-height:var(--nav-height);padding:var(--space-xs) var(--space-xs) var(--space-xs) var(--space-md);border:var(--rule-thin) solid var(--color-rule);border-radius:var(--radius-round);background:color-mix(in oklch,var(--color-paper-2) 88%,transparent);box-shadow:0 var(--space-xs) var(--space-xl) color-mix(in oklch,var(--color-shadow) 64%,transparent);backdrop-filter:blur(14px) saturate(120%);transform:translateX(-50%)}.wordmark{font:700 var(--text-base)/1 var(--font-display);letter-spacing:-.03em}.nav-note{display:none;color:var(--color-muted);font:600 var(--text-xs)/1 var(--font-mono);letter-spacing:.06em}.nav-action{display:inline-grid;min-height:2.25rem;place-items:center;padding-inline:var(--space-md);border-radius:var(--radius-round);background:var(--color-accent);color:var(--color-paper);font-weight:700;text-decoration:none}.nav-action:hover{color:var(--color-paper-2)}
.hero{position:relative;display:grid;min-height:82dvh;align-content:end;padding-block:calc(var(--space-4xl) + var(--nav-height)) var(--space-2xl)}.hero h1{position:relative;z-index:var(--z-raised);max-width:9.5ch;margin:0;font:700 var(--text-display)/.88 var(--font-display);letter-spacing:-.06em;overflow-wrap:anywhere;min-width:0}.hero h1 span{display:block;color:var(--color-accent-soft);font-size:clamp(2.25rem,9vw,7rem);white-space:nowrap;text-decoration:underline;text-decoration-color:var(--color-accent);text-decoration-thickness:var(--rule-thick);text-underline-offset:var(--space-xs)}.familiar{position:absolute;inset-block-start:calc(var(--space-3xl) + var(--nav-height));inset-inline-end:3%;display:grid;width:calc(var(--logo-size) + var(--space-2xl));aspect-ratio:1;place-items:center;border:var(--rule-thin) solid var(--color-rule);border-radius:var(--radius-round);background:color-mix(in oklch,var(--color-paper-2) 72%,transparent)}.familiar::before,.familiar::after{content:"";position:absolute;border-radius:var(--radius-round);pointer-events:none}.familiar::before{inset:var(--space-sm);border:var(--rule-thin) solid var(--color-rule);transform:rotate(-18deg) scaleY(.48)}.familiar::after{width:var(--space-xs);height:var(--space-xs);inset-block-start:8%;inset-inline-end:18%;background:var(--color-accent-soft)}.logo-loop{display:block;width:var(--logo-size);height:var(--logo-size);object-fit:cover;border-radius:var(--radius-round);background:var(--color-code)}.hero-mark{position:absolute;inset-block-end:var(--space-2xl);inset-inline-end:0;max-width:7ch;margin:0;color:var(--color-accent);font:700 var(--text-xl)/.9 var(--font-display);letter-spacing:-.06em;text-align:end}
.scale-marquee{margin-inline:calc(50% - 50vw);overflow:hidden;border-block:var(--rule-thin) solid var(--color-rule);background:var(--color-scale-paper);color:var(--color-scale-ink)}.scale-marquee-track{--marquee-distance:50%;display:flex;width:max-content;animation:marquee 28s linear infinite}.scale-marquee-set{display:flex;align-items:stretch;margin:0;padding:0;white-space:nowrap}.scale-marquee-item{display:inline-flex;align-items:center;gap:var(--space-sm);padding:var(--space-lg) var(--space-xl);border-inline-end:var(--rule-thin) solid color-mix(in oklch,var(--color-scale-ink) 16%,transparent);font:400 var(--text-base)/1 var(--font-body)}.scale-marquee-item strong{color:var(--color-scale-pink);font:600 var(--text-lg)/1 var(--font-mono);letter-spacing:-.05em}.scale-marquee-icon{font-size:var(--text-lg)}.scale-marquee-separator{display:grid;place-items:center;padding-inline:var(--space-xs);color:var(--color-scale-teal);font-size:var(--text-md)}.scale-marquee:hover .scale-marquee-track{animation-play-state:paused}@keyframes marquee{to{transform:translateX(calc(var(--marquee-distance)*-1))}}
.ritual{margin-inline:calc(50% - 50vw);padding:var(--space-3xl) max(var(--space-lg),calc((100vw - var(--shell))/2));background:var(--color-paper-2)}.ritual-intro{display:grid;gap:var(--space-lg);margin-block-end:var(--space-2xl)}.ritual h2{margin:0;font:700 var(--text-2xl)/1.02 var(--font-display);letter-spacing:-.04em;overflow-wrap:anywhere;min-width:0}.ritual-intro p{max-width:52ch;margin:0;color:var(--color-muted);font-size:var(--text-md)}.ritual-grid{display:grid}.request{min-width:0;margin:0;padding:var(--space-lg);overflow:auto;border-radius:var(--radius-card);background:var(--color-code);color:var(--color-code-ink);font:var(--text-sm)/1.72 var(--font-mono);tab-size:2}.request::before{content:"POST /v1/chat/completions";display:block;margin-block-end:var(--space-lg);color:var(--color-accent-soft);font-weight:600;letter-spacing:.04em}
.footer{display:grid;gap:var(--space-2xl);padding-block:var(--space-3xl) max(var(--space-xl),env(safe-area-inset-bottom));border-block-start:var(--rule-thick) solid var(--color-rule)}.footer-line{max-width:18ch;margin:0;font:700 var(--text-2xl)/1.02 var(--font-display);letter-spacing:-.04em}.footer-meta{display:flex;align-items:center;flex-wrap:wrap;justify-content:space-between;gap:var(--space-md);color:var(--color-muted);font-size:var(--text-sm)}
.reveal{opacity:0;animation:reveal var(--dur-long) var(--ease-out) forwards;animation-delay:calc(var(--i,0)*60ms)}@keyframes reveal{to{opacity:1}}
@media(min-width:40rem){.nav-note{display:block}.familiar{width:calc(var(--logo-size-wide) + var(--space-2xl))}.logo-loop{width:var(--logo-size-wide);height:var(--logo-size-wide)}.hero-mark{max-width:18ch}.ritual-intro{grid-template-columns:minmax(0,.9fr) minmax(0,1.1fr);align-items:end}}
@media(min-width:60rem){.hero{min-height:76dvh}.ritual-grid{grid-template-columns:minmax(0,1fr)}}
.hero{min-height:76dvh;padding-block:calc(var(--space-xl) + var(--nav-height)) var(--space-3xl)}.hero h1 span{text-underline-offset:var(--space-3xs)}.nav-note,.hero-mark{font-family:var(--font-body)}.nav-action,.nav-action:hover{color:var(--color-accent-ink)}a[aria-disabled="true"]{color:var(--color-muted);cursor:not-allowed;pointer-events:none}.hero-mark{display:none}@media(min-width:40rem){.hero-mark{display:block}}
.hero{justify-items:start;row-gap:var(--space-lg)}.hero h1 em{display:block;max-width:13ch;margin-block-start:var(--space-sm);color:var(--color-ink);font:700 var(--text-xl)/.96 var(--font-display);font-style:normal;letter-spacing:-.04em}.hero-paper{position:relative;z-index:var(--z-raised);display:inline-flex;align-items:center;gap:var(--space-xs);padding:var(--space-sm) var(--space-md);border:var(--rule-thin) solid var(--color-rule);border-radius:var(--radius-sm);background:var(--color-paper-2);box-shadow:var(--space-3xs) var(--space-3xs) 0 var(--color-rule);font:700 var(--text-sm)/1 var(--font-mono);text-decoration:none}.hero-paper:hover{color:var(--color-accent);transform:translate(-1px,-1px);box-shadow:var(--space-2xs) var(--space-2xs) 0 var(--color-rule)}
.nav{border-radius:var(--radius-sm)}.nav-action{border-radius:var(--space-xs)}
@media(pointer:coarse){.nav-action{min-height:2.75rem}}
@media(prefers-reduced-motion:reduce){*,*::before,*::after{animation-duration:150ms!important;animation-iteration-count:1!important;transition-duration:150ms!important}.reveal{animation:reveal 150ms linear forwards}.scale-marquee-track{width:auto;animation:none}.scale-marquee-set{flex-wrap:wrap;justify-content:center;white-space:normal}.scale-marquee-set[aria-hidden="true"]{display:none}}
</style></head><body><nav class="nav" aria-label="Primary"><span class="wordmark">biggie-kun</span><span class="nav-note">1B tokens</span><a class="nav-action" href="#summon">Try</a></nav><div class="shell"><main><header class="hero reveal" style="--i:0"><div class="familiar" aria-hidden="true"><video class="logo-loop" autoplay muted loop playsinline preload="metadata" poster="/logo-loop.webp" fetchpriority="high"><source src="/logo-loop.mp4" type="video/mp4"></video></div><h1><span>1,000,000,000</span> context window model.</h1><p class="hero-mark">1 BILLION</p></header><section class="scale-marquee" aria-label="Context scale"><div class="scale-marquee-track"><p class="scale-marquee-set"><span class="scale-marquee-item"><span class="scale-marquee-icon" aria-hidden="true">◯</span><strong>1,000×</strong> a 1M context</span><span class="scale-marquee-separator" aria-hidden="true">✦</span><span class="scale-marquee-item"><span class="scale-marquee-icon" aria-hidden="true">📖</span><strong>≈750M</strong> words</span><span class="scale-marquee-separator" aria-hidden="true">✦</span><span class="scale-marquee-item"><span class="scale-marquee-icon" aria-hidden="true">📚</span><strong>≈9,000</strong> novels</span><span class="scale-marquee-separator" aria-hidden="true">✦</span></p><p class="scale-marquee-set" aria-hidden="true" data-marquee-clone><span class="scale-marquee-item"><span class="scale-marquee-icon" aria-hidden="true">◯</span><strong>1,000×</strong> a 1M context</span><span class="scale-marquee-separator" aria-hidden="true">✦</span><span class="scale-marquee-item"><span class="scale-marquee-icon" aria-hidden="true">📖</span><strong>≈750M</strong> words</span><span class="scale-marquee-separator" aria-hidden="true">✦</span><span class="scale-marquee-item"><span class="scale-marquee-icon" aria-hidden="true">📚</span><strong>≈9,000</strong> novels</span><span class="scale-marquee-separator" aria-hidden="true">✦</span></p></div></section><section class="ritual" id="summon" aria-labelledby="summon-heading"><div class="ritual-intro"><h2 id="summon-heading">Send everything.</h2><p>One normal chat request. No uploads. No sessions. No vector store.</p></div><div class="ritual-grid"><pre class="request"><code>curl -N https://biggie-kun-vps.sharath.page/v1/chat/completions \
  -H 'content-type: application/json' \
  -d '{
    "model": "biggie-kun",
    "stream": true,
    "messages": [
      {"role":"user","content":"The launch window is 04:30 UTC."},
      {"role":"user","content":"When is launch?"}
    ]
  }'</code></pre></div></section></main><footer class="footer"><p class="footer-line">Big context. Simple chat.</p><div class="footer-meta"><span>biggie-kun · MIT · one billion tokens</span><a href="https://github.com/tnfssc/biggie-kun">Source</a></div></footer></div><script>(()=>{const video=document.querySelector('.logo-loop');const reduced=matchMedia('(prefers-reduced-motion: reduce)');const saver=navigator.connection?.saveData;const syncVideo=()=>{if(reduced.matches||saver){video.pause();video.removeAttribute('autoplay')}else{video.setAttribute('autoplay','');video.play().catch(()=>{})}};const track=document.querySelector('.scale-marquee-track');const seed=track?.querySelector('.scale-marquee-set');const fillMarquee=()=>{if(!track||!seed)return;track.querySelectorAll('[data-marquee-clone]').forEach(node=>node.remove());const width=Math.ceil(seed.getBoundingClientRect().width);if(!width)return;const copies=Math.ceil(innerWidth/width)+1;for(let i=0;i<copies;i++){const clone=seed.cloneNode(true);clone.setAttribute('aria-hidden','true');clone.dataset.marqueeClone='';track.append(clone)}track.style.setProperty('--marquee-distance',width+'px')};syncVideo();fillMarquee();document.fonts?.ready.then(fillMarquee);addEventListener('resize',fillMarquee,{passive:true});reduced.addEventListener?.('change',syncVideo)})()</script></body></html>`, "{{TOKENS}}", tokensCSS, 1)

const FaviconSVG = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><rect width="512" height="512" rx="112" fill="#f7f4e8"/><ellipse cx="256" cy="270" rx="168" ry="158" fill="#fffef6" stroke="#1a2744" stroke-width="22"/><ellipse cx="206" cy="242" rx="20" ry="26" fill="#1a2744"/><ellipse cx="306" cy="242" rx="20" ry="26" fill="#1a2744"/><path d="M218 302 C234 328 278 328 294 302" fill="none" stroke="#1a2744" stroke-width="18" stroke-linecap="round"/></svg>`

func init() {
	const oldHeadline = `<h1><span>1,000,000,000</span> context window model.</h1>`
	const headline = `<h1><span>1-Billion-Token</span> Context Window. <em>It’s Absolutely Unreal.</em></h1>`
	const paperLink = `<a class="hero-paper" href="https://doi.org/10.5281/zenodo.21852829" target="_blank" rel="noreferrer">Read the paper.pdf <span aria-hidden="true">↗</span></a>`
	LandingHTML = strings.Replace(LandingHTML, oldHeadline, headline+paperLink, 1)
	LandingHTML = strings.Replace(LandingHTML, `<title>biggie-kun · big context, one chat</title>`, `<title>1-Billion-Token Context Window · biggie-kun</title>`, 1)
}
