package biggie

import (
	_ "embed"
	"strings"
)

//go:embed tokens.css
var tokensCSS string

var LandingHTML = strings.Replace(`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>biggie-kun · 1B token context</title><meta name="description" content="OpenAI-compatible chat with a billion-token context.">
<link rel="icon" href="/favicon.svg"><link rel="preload" href="/logo-loop.webp" as="image" type="image/webp" fetchpriority="high"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;700&family=JetBrains+Mono:wght@400;600&family=Space+Grotesk:wght@700&display=swap" rel="stylesheet">
<style>{{TOKENS}}
*{box-sizing:border-box}html,body{overflow-x:clip}body{margin:0;background:var(--color-paper);color:var(--color-ink);font:var(--text-base)/1.6 var(--font-body);font-variant-numeric:oldstyle-nums}a{color:inherit;text-decoration-thickness:var(--rule-thin);text-underline-offset:var(--space-2xs);white-space:nowrap}a:hover{color:var(--color-accent)}a:focus-visible{outline:var(--rule-focus) solid var(--color-focus);outline-offset:var(--space-2xs)}a:active{color:var(--color-focus)}a[aria-disabled="true"]{color:var(--color-rule);cursor:not-allowed;pointer-events:none}
.shell{width:min(var(--shell),calc(100% - var(--space-xl)));margin-inline:auto}.nav{display:flex;align-items:center;justify-content:space-between;padding-block:var(--space-lg);border-block-end:var(--rule-thin) solid var(--color-rule)}.wordmark{font:700 var(--text-md)/1 var(--font-display);letter-spacing:-.03em}.status{display:none;font:600 var(--text-xs)/1 var(--font-mono);color:var(--color-muted);letter-spacing:.08em;text-transform:uppercase}
.hero{display:grid;gap:var(--space-2xl);padding-block:var(--space-3xl) var(--space-4xl)}.hero h1{max-width:12ch;margin:0;font:700 var(--text-display)/.98 var(--font-display);letter-spacing:-.055em;overflow-wrap:anywhere;min-width:0}.hero h1 span{text-decoration:underline;text-decoration-color:var(--color-accent);text-decoration-thickness:var(--rule-thick);text-underline-offset:var(--space-3xs)}.hero-side{display:flex;flex-direction:column;align-items:flex-start;gap:var(--space-lg)}.logo-loop{display:block;width:var(--logo-size);height:var(--logo-size);object-fit:cover;border:var(--rule-thin) solid var(--color-rule);border-radius:var(--radius-round);background:var(--color-code)}.lead{max-width:45ch;margin:0;color:var(--color-muted);font-size:var(--text-lg);line-height:1.45}
.bench{padding-block-end:var(--space-4xl)}.bench h2{max-width:20ch;margin:0 0 var(--space-xl);font:700 var(--text-2xl)/1.1 var(--font-display);letter-spacing:-.035em;overflow-wrap:anywhere;min-width:0}.bench-grid{display:grid;gap:var(--space-xl)}.request{min-width:0;margin:0;padding:var(--space-lg);overflow:auto;border-block:var(--rule-thin) solid var(--color-rule);background:var(--color-code);color:var(--color-code-ink);font:var(--text-sm)/1.7 var(--font-mono);tab-size:2}.request::before{content:"POST /v1/chat/completions";display:block;margin-block-end:var(--space-lg);color:var(--color-accent-soft);font-weight:600}.spec{margin:0;border-block-start:var(--rule-thin) solid var(--color-rule)}.spec div{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:var(--space-md);padding-block:var(--space-md);border-block-end:var(--rule-thin) solid var(--color-rule)}.spec dt{color:var(--color-muted)}.spec dd{margin:0;font-variant-numeric:tabular-nums}
.reason{display:grid;gap:var(--space-lg);padding-block:var(--space-3xl);border-block-start:var(--rule-thick) solid var(--color-ink)}.reason h2{margin:0;font:700 var(--text-2xl)/1.1 var(--font-display);letter-spacing:-.035em;overflow-wrap:anywhere;min-width:0}.reason p{max-width:62ch;margin:0;color:var(--color-muted)}.reason code{font-family:var(--font-mono);color:var(--color-ink)}.footer{display:flex;align-items:center;flex-wrap:wrap;justify-content:space-between;gap:var(--space-md);padding-block:var(--space-xl);border-block-start:var(--rule-thin) solid var(--color-rule);color:var(--color-muted);font-size:var(--text-sm)}
@media(min-width:48rem){.status{display:block}.hero{grid-template-columns:minmax(0,1.25fr) minmax(0,.75fr)}.hero-side{align-items:flex-end;justify-content:space-between}.logo-loop{width:var(--logo-size-wide);height:var(--logo-size-wide)}.bench-grid{grid-template-columns:minmax(0,1.7fr) minmax(15rem,.65fr)}.reason{grid-template-columns:minmax(0,.7fr) minmax(0,1.3fr);align-items:start}}
@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}}
</style></head><body><div class="shell"><nav class="nav" aria-label="Primary"><div class="wordmark">biggie-kun</div><div class="status">1B context · OpenAI-compatible · no auth</div></nav><main><header class="hero"><h1><span>1 billion</span> tokens, one chat.</h1><div class="hero-side"><video class="logo-loop" autoplay muted loop playsinline preload="metadata" poster="/logo-loop.webp" aria-label="Animated biggie-kun logo"><source src="/logo-loop.mp4" type="video/mp4"></video><p class="lead">Bring the whole conversation. Ask anything inside it. biggie-kun handles it like a normal chat model.</p></div></header><section class="bench" aria-labelledby="try-heading"><h2 id="try-heading">Call the whole thing with curl.</h2><div class="bench-grid"><pre class="request"><code>curl -N http://127.0.0.1:11500/v1/chat/completions \
  -H 'content-type: application/json' \
  -d '{
    "model": "biggie-kun",
    "stream": true,
    "messages": [
      {"role":"user","content":"The launch window is 04:30 UTC."},
      {"role":"user","content":"When is launch?"}
    ]
  }'</code></pre><dl class="spec"><div><dt>JSON body</dt><dd>4.1 GB</dd></div><div><dt>Context</dt><dd>1B tokens</dd></div><div><dt>Link pace</dt><dd>32 Mbit/s</dd></div><div><dt>Streaming</dt><dd>SSE</dd></div><div><dt>API</dt><dd>OpenAI-compatible</dd></div></dl></div></section><section class="reason"><h2>Reasoning arrives live.</h2><p>Stream <code>reasoning_content</code> as the model thinks, followed by the final answer. Disable it whenever you only want content.</p></section></main><footer class="footer"><span>biggie-kun · 1B-context model</span><a href="https://github.com/tnfssc/biggie-kun">Source on GitHub</a></footer></div><script>(()=>{const video=document.querySelector('.logo-loop');const reduced=matchMedia('(prefers-reduced-motion: reduce)');const sync=()=>{if(reduced.matches){video.pause();video.removeAttribute('autoplay')}else{video.setAttribute('autoplay','');video.play().catch(()=>{})}};sync();reduced.addEventListener?.('change',sync)})()</script></body></html>`, "{{TOKENS}}", tokensCSS, 1)

const FaviconSVG = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><rect width="512" height="512" rx="112" fill="#f7f4e8"/><ellipse cx="256" cy="270" rx="168" ry="158" fill="#fffef6" stroke="#1a2744" stroke-width="22"/><ellipse cx="206" cy="242" rx="20" ry="26" fill="#1a2744"/><ellipse cx="306" cy="242" rx="20" ry="26" fill="#1a2744"/><path d="M218 302 C234 328 278 328 294 302" fill="none" stroke="#1a2744" stroke-width="18" stroke-linecap="round"/></svg>`
